# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmi2ip306OZN-T-o-9GwBLdMg-9jULsL
"""

import requests

crypto_id = input("Введіть код криптовалюти: ")

url = f"https://api.coingecko.com/api/v3/coins/{crypto_id}"

try:
    response = requests.get(url)
    response.raise_for_status()

    data = response.json()

    name = data["name"]
    symbol = data["symbol"]
    description = data["description"]["en"]

    print("\nІнформація про криптовалюту:")
    print(f"Назва: {name}")
    print(f"Символ: {symbol}")
    print(f"Опис: {description[:300]}")

except requests.exceptions.RequestException as e:
    print(f"Помилка запиту: {e}")

except KeyError:
    print("Помилка обробки JSON.")